version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

    volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ecom
networks:
  ecom:
    external: true
