version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf # Optional: if you have a custom nginx.conf
