version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "80:80"
    networks:
      - ecom
    volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  ecom:
    external: true
